FROM ubuntu

RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev tree

WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt
RUN pip3 install pymongo[srv]
RUN pip3 install lxml
RUN pip3 install gunicorn
COPY . /app/nba-match-predictor
EXPOSE 5000
# launch app
ENV FLASK_APP=app.py
CMD ["python3", "-b", "/app/nba-match-predictor/api/app.py"]